services:
  random-image-server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      # Mount all the local images, PDFs, and directories configured in your config file to the container
      - ./assets:/assets
